# Roles
SYSTEM_ADMIN = "SYSTEM_ADMIN"
HOSPITAL_ADMIN = "HOSPITAL_ADMIN"
DOCTOR = "DOCTOR"
RECEPTIONIST = "RECEPTIONIST"

# Appointment Status
APPOINTMENT_BOOKED = "BOOKED"
APPOINTMENT_COMPLETED = "COMPLETED"
APPOINTMENT_CANCELLED = "CANCELLED"
